." Last modification 23.04.2016 @ Schnusch
.TH bdinfo 1 "2018-02-19" "V1.0" "bdinfo manpage"


.SH NAME

bdinfo \- bluray information and extraction


.SH DESCRIPTION

bdinfo is a command-line tool for extracting information about and metadata from Blu-rays or remuxing selected streams using ffmpeg.
.br
The main reason for using bdinfo is that ffmpeg at the moment is unable to extract metadata itself.
.br
Moreover bdinfo provies an easy way for scripted extraction using its
.I YAML
output.
.br
Note: There is absolutely no copy protection circumvention!


.SH SYNOPSIS
.SY bdinfo
.OP \-achiLsv
.OP \-t DURATION
.OP \-p PLAYLIST\fR[:\fIANGLE\fR]
.OP \-f\fR[\fILANGUAGES\fR]
.OP \-x\fR[\fILANGUAGES\fR]
.I INPUT
.RI [ OUTPUT \fR]
.YS

Note: \fIINPUT\fR is the root directory of the Blu-ray or, if your distribution's libbluray supports it, a Blu-ray image.


.SH OPTIONS

.IP "\fB\-t, \-\-time\fR=\fIDURATION\fR"
Select all titles which are at least
.I DURATION
seconds long
.IP "\fB\-p, \-\-playlist\fR=\fIPLAYLIST\fR[\fI:ANGLE\fR]"
Select playlist
.I PLAYLIST
and all angles unless
.I ANGLE
is specified,
.br
in that case only the given angle is selected.
.IP "\fB\-a, \-\-all"
Select all titles, do not omit duplicates
.IP "\fB\-i, \-\-info"
List extended information for all selected titles
.IP "\fB\-c, \-\-chapters"
Print chapters-xml to stdout
.IP "\fB\-f, \-\-ffmpeg\fR[=\fILANGUAGES\fR]"
Print ffmpeg command for extracting streams,
.br
which language-tags match one of \fILANGUAGES\fR or are \fIundefined\fR.


.B \fILANGUAGES\fR
is a comma-separated list of ISO 639-2 language-tags,
.br
e.g. \fIger,eng\fR for German and English languages.


Note: \fIOUTPUT\fR, which defines the output file, is required.
.IP "\fB\-x, \-\-remux\fR[=\fILANGUAGES\fR]"
Extract streams which language-tags match one of
.I LANGUAGES
or are \fIundefined\fR into \fIOUTPUT\fR.
.br
The ffmpeg command displayed by \fB\-f\fR is executed.
.IP "\fB\-L, \-\-lossless"
transcode lossless audio tracks to FLAC
.IP "\fB\-s, \-\-skip-igs"
skip interactive graphic streams on extraction
.IP "\fB-h, --help"
Show basic command-line help
.IP "\fB-v, --version"
Show version and license information


.SH AUTHOR

Schnusch \fB\-\fR Author of bdinfo
.br
Ferdinand Thiessen \fB-\fR Contributor to bdinfo and original author of this manpage


.SH SEE ALSO

.UR "https://github.com/\:Schnusch/\:bdinfo
Visit the GitHub page
.UE ,
for updates and other information.
